### ISSUE TITLE
Create a convincing story for handling build.rs scripts

### ISSUE THREAD

**Issue by acmcarther** [acmcarther/cargo-raze#13]
This is a vague issue, created around my experience of overriding stuff to support openssl. Historically, my approach has been to try to execute the build.rs scripts, but often I think it is more appropriate to perform the steps manually. This is because often the upstream dependency (in this case, the openssl C lib) is actually in the mono repo, so the dynamic configuration is unnecessary.

Here was the process for openssl:

1) Pull down openssl tar and unpack it into the monorepo.
2) Build it, either by manually crafting a build rule with the desired settings, or by building it with make. Either way, produce a `.a` file. My build file was as follows:
```python
package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_library(
    name = "crypto",
    srcs = [
        "libcrypto.a",
    ]
)

cc_library(
    name = "ssl",
    srcs = [
        "libssl.a",
    ]
)
```
3) Remove openssl and openssl's build_script entries in BUILD. Add deps to openssl_sys for crypto and ssl, and update the cfg flags. The full entries are:
```python
rust_library(
    name = "openssl_sys",
    crate_root = "src/lib.rs",
    srcs = glob(["**/*.rs"]),
    deps = [
      "//cargo/vendor/libc-0.2.33:libc",
      "//third_party/openssl/openssl-1.1.0g:crypto",
      "//third_party/openssl/openssl-1.1.0g:ssl",
    ],
    rustc_flags = [
        "--cap-lints allow",
        "--target=x86_64-unknown-linux-gnu",
        "--cfg=ossl110",
        "--cfg=version=110",
    ],
    crate_features = [],
)
```
and
```python
rust_library(
    name = "openssl",
    crate_root = "src/lib.rs",
    srcs = glob(["**/*.rs"]),
    deps = [
      "//cargo/vendor/bitflags-0.9.1:bitflags",
      "//cargo/vendor/foreign-types-0.2.0:foreign_types",
      "//cargo/vendor/lazy_static-0.2.11:lazy_static",
      "//cargo/vendor/libc-0.2.33:libc",
      "//cargo/vendor/openssl-sys-0.9.21:openssl_sys",
    ],
    rustc_flags = [
        "--cap-lints allow",
        "--target=x86_64-unknown-linux-gnu",
        "--cfg=ossl110",
    ],
    crate_features = [],
)
```
---
I'm thinking perhaps including customizations in the Cargo.toml might be a good step. Here is a sample schema
```toml
[raze.crates.normalized_crate_name.0.9.2.override]
use_build_rs = false
include_examples = false
include_tests = false
additional_deps = [
  "//third_party/openssl/openssl-1.1.0g:crypto",
  "//third_party/openssl/openssl-1.1.0g:ssl",
]
additional_flags = [
  "--cfg=ossl110",
]
```

Transitive dependencies need to be affectable in this way -- I'll observe no difference between them and explicit deps.
